packages:
  - docs
  - packages/**
  - e2e/*
  - e2e/*/fragments/*
  - e2e/node-servers/**/*

catalog:
  typescript: 5.5.4
  vite: 6.0.7
  wrangler: 3.109.3
  '@playwright/test': 1.49.1
  '@cloudflare/workers-types': 4.20250224.0
