name: Web Fragments Tests

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/playwright-web-fragments.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/playwright-web-fragments.yml'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'packages/web-fragments'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(cat ../../pnpm-workspace.yaml | grep playwright | cut -d' ' -f4)" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: pnpm -C test/playground exec playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: pnpm test:playground

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test/playground/node_modules/.wf-playground-tests/playwright-report/
          retention-days: 30
